In [4]:
# check the max value in elements of files in a directory
import os
import sys

directory = "./generated_FMTV_data/task_execution_time/"
max_value = 0
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        # print(filename)
        with open(directory + filename, 'r') as file:
            for line in file:
                for value in line.split(','):
                    if int(value) > max_value:
                        max_value = int(value)
print(max_value)

Task_1000ms.csv
ISR_11.csv
ISR_5.csv
ISR_10.csv
Task_200ms.csv
ISR_7.csv
Task_100ms.csv
Task_20ms.csv
Task_2ms.csv
ISR_9.csv
ISR_4.csv
ISR_1.csv
Task_10ms.csv
Task_50ms.csv
ISR_6.csv
ISR_3.csv
ISR_2.csv
ISR_8.csv
Task_5ms.csv
Task_1ms.csv
Angle_Sync.csv
17431910


In [8]:
import os
import sys
import numpy as np

org_directory = "./generated_FMTV_data/task_execution_time/"
phased_directory = "./generated_FMTV_data/task_execution_time_phased/"

max_value_phased = 0
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        print(filename)
        # read csv to numpy array
        runnable_info = np.genfromtxt(org_directory + filename, delimiter=',')
        # sum columns
        sum_org = np.sum(runnable_info, axis=0)      
        max_value_file = np.max(sum_org)
        if max_value_file > max_value_phased:
            max_value_phased = max_value_file
print(max_value_phased)

Task_1000ms.csv
ISR_11.csv
ISR_5.csv
ISR_10.csv
Task_200ms.csv
ISR_7.csv
Task_100ms.csv
Task_20ms.csv
Task_2ms.csv
ISR_9.csv
ISR_4.csv
ISR_1.csv
Task_10ms.csv
Task_50ms.csv
ISR_6.csv
ISR_3.csv
ISR_2.csv
ISR_8.csv
Task_5ms.csv
Task_1ms.csv
Angle_Sync.csv
76002865.0


In [7]:
import numpy as np
org_test = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(org_test)

sum_org = np.sum(org_test, axis=0)
print(sum_org)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
